apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-pv
  namespace: tomato
  labels:
    name: host-path-pv
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /root/storage