apiVersion: v1
kind: Service
metadata:
  namespace: tomato
  name: zookeeper
  labels:
    name: zookeeper
spec:
  clusterIP: None
  ports:
    - name: zookeeper-port
      port: 2181
  selector:
    app: zookeeper