apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-path-pv-1
  namespace: tomato
  labels:
    name: host-path-pv-1
spec:
  storageClassName: manual
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /root/storage/data-1